/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;


public class NewJFrame extends javax.swing.JFrame {

    
    private static final Graph.Edge[] GRAPH = {
		 new Graph.Edge("Gdansk", "Szczecin", 353),
			new Graph.Edge("Gdansk", "Bydgoszcz", 167),
			new Graph.Edge("Gdansk", "Olsztyn", 160),

			new Graph.Edge("Szczecin", "Gorzow Wielkopolski", 105),
			new Graph.Edge("Szczecin", "Poznan", 244),
			new Graph.Edge("Szczecin", "Bydgoszcz", 257),
			new Graph.Edge("Szczecin", "Gdansk", 353),

			new Graph.Edge("Bydgoszcz", "Lodz", 215),
			new Graph.Edge("Bydgoszcz", "Gdansk", 167),
			new Graph.Edge("Bydgoszcz", "Olsztyn", 213),
			new Graph.Edge("Bydgoszcz", "Warsaw", 272),
			new Graph.Edge("Bydgoszcz", "Poznan", 142),
			new Graph.Edge("Bydgoszcz", "Szczecin", 257),

			new Graph.Edge("Gorzow Wielkopolski", "Szczecin", 105),
			new Graph.Edge("Gorzow Wielkopolski", "Poznan", 137),
			new Graph.Edge("Gorzow Wielkopolski", "Wroclaw", 262),

			new Graph.Edge("Lodz", "Kielce", 159),
			new Graph.Edge("Lodz", "Bydgoszcz", 215),
			new Graph.Edge("Lodz", "Warsaw", 152),
			new Graph.Edge("Lodz", "Opole", 204),
			new Graph.Edge("Lodz", "Katowice", 198),
			new Graph.Edge("Lodz", "Krakow", 241),
			new Graph.Edge("Lodz", "Wroclaw", 217),
			new Graph.Edge("Lodz", "Poznan", 205),

			new Graph.Edge("Kielce", "Krakow", 116),
			new Graph.Edge("Kielce", "Lodz", 159),
			new Graph.Edge("Kielce", "Warsaw", 179),
			new Graph.Edge("Kielce", "Lublin", 179),
			new Graph.Edge("Kielce", "Rzeszow", 157),

			new Graph.Edge("Warsaw", "Lublin", 171),
			new Graph.Edge("Warsaw", "Kielce", 179),
			new Graph.Edge("Warsaw", "Bialystok", 198),
			new Graph.Edge("Warsaw", "Olsztyn", 210),
			new Graph.Edge("Warsaw", "Bydgoszcz", 272),
			new Graph.Edge("Warsaw", "Lodz", 152),

			new Graph.Edge("Olsztyn", "Warsaw", 210),
			new Graph.Edge("Olsztyn", "Gdansk", 160),
			new Graph.Edge("Olsztyn", "Bialystok", 228),
			new Graph.Edge("Olsztyn", "Bydgoszcz", 213),

			new Graph.Edge("Bialystok", "Olsztyn", 213),
			new Graph.Edge("Bialystok", "Lublin", 246),
			new Graph.Edge("Bialystok", "Warsaw", 198),

			new Graph.Edge("Lublin", "Bialystok", 246),
			new Graph.Edge("Lublin", "Rzeszow", 163),
			new Graph.Edge("Lublin", "Kielce", 179),
			new Graph.Edge("Lublin", "Warsaw", 171),

			new Graph.Edge("Rzeszow", "Krakow", 173),
			new Graph.Edge("Rzeszow", "Kielce", 157),
			new Graph.Edge("Rzeszow", "Lublin", 163),

			new Graph.Edge("Wroclaw", "Gorzow Wielkopolski", 262),
			new Graph.Edge("Wroclaw", "Poznan", 176),
			new Graph.Edge("Wroclaw", "Opole", 100),
			new Graph.Edge("Wroclaw", "Lodz", 217),

			new Graph.Edge("Poznan", "Wroclaw", 176),
			new Graph.Edge("Poznan", "Gorzow Wielkopolski", 137),
			new Graph.Edge("Poznan", "Szczecin", 244),
			new Graph.Edge("Poznan", "Bydgoszcz", 142),
			new Graph.Edge("Poznan", "Lodz", 205),
			new Graph.Edge("Poznan", "Opole", 244),

			new Graph.Edge("Opole", "Wroclaw", 100),
			new Graph.Edge("Opole", "Lodz", 204),
			new Graph.Edge("Opole", "Katowice", 107),
			new Graph.Edge("Opole", "Poznan", 244),

			new Graph.Edge("Katowice", "Opole", 107),
			new Graph.Edge("Katowice", "Krakow", 79),
			new Graph.Edge("Katowice", "Lodz", 198),

			new Graph.Edge("Krakow", "Katowice", 79),
			new Graph.Edge("Krakow", "Kielce", 116),
			new Graph.Edge("Krakow", "Rzeszow", 173),
			new Graph.Edge("Krakow", "Lodz", 241),
	      };
    Graph g = new Graph(GRAPH);
    public NewJFrame() {
        
        initComponents();
        setSize(530, 470);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CitiesGroup = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Gdansk = new javax.swing.JButton();
        Szczecin = new javax.swing.JButton();
        From = new javax.swing.JTextField();
        To = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("From"); // NOI18N
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Szczecin", "Bialystok", "Lublin", "Rzeszow", "Katowice", "Opole", "Gorzow Wielkopolski", "Koszalin", "Olsztyn ", "Kielce", "Bydgoszcz" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(110, 20, 90, 20);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan", "Gdansk", "Szczecin", "Bialystok", "Lublin", "Rzeszow", "Katowice", "Opole", "Gorzow Wielkopolski", "Koszalin", "Olsztyn ", "Kielce", "Bydgoszcz" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(260, 20, 100, 20);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 20, 61, 23);

        jLabel3.setText("To");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(222, 20, 20, 14);

        jLabel1.setText("From");
        jLabel1.setToolTipText("");
        jLabel1.setName("From"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 20, 24, 14);
        jLabel1.getAccessibleContext().setAccessibleDescription("From");

        Gdansk.setToolTipText("");
        Gdansk.setActionCommand("Gdansk");
        Gdansk.setBorderPainted(false);
        CitiesGroup.add(Gdansk);
        Gdansk.setContentAreaFilled(false);
        Gdansk.setOpaque(false);
        Gdansk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GdanskActionPerformed(evt);
            }
        });
        getContentPane().add(Gdansk);
        Gdansk.setBounds(210, 70, 70, 20);

        Szczecin.setBorderPainted(false);
        CitiesGroup.add(Szczecin);
        Szczecin.setContentAreaFilled(false);
        Szczecin.setDefaultCapable(false);
        Szczecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzczecinActionPerformed(evt);
            }
        });
        getContentPane().add(Szczecin);
        Szczecin.setBounds(30, 140, 33, 9);

        From.setText("                   ");
        From.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(From);
        From.setBounds(120, 50, 63, 20);

        To.setText("                ");
        To.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(To);
        To.setBounds(270, 50, 54, 20);

        Back.setForeground(new java.awt.Color(51, 51, 255));
        Back.setIcon(new javax.swing.ImageIcon("E:\\Java\\Twilight\\src\\map.png")); // NOI18N
        Back.setText("jLabel2");
        Back.setToolTipText("");
        getContentPane().add(Back);
        Back.setBounds(0, 0, 520, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String SelectFrom = (String) From.getText();
		 				String SelectTo= (String) To.getText();
		 				JOptionPane.showMessageDialog(NewJFrame.this,
		 						"from " + SelectFrom + " to " + SelectTo);
		 					g.dijkstra(SelectFrom);
		 					g.printPath(SelectTo);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       String from = (String)jComboBox1.getSelectedItem();
	DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) jComboBox1.getModel();
	From.setText( from);
					int selectedIndex = model.getIndexOf(from);
					if (selectedIndex < 0) {
						// if the selected book does not exist before, 
						// add it into this combo box
						model.addElement(from);
					}
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
         String to = (String)jComboBox2.getSelectedItem();
	DefaultComboBoxModel<String> model = (DefaultComboBoxModel<String>) jComboBox2.getModel();
	To.setText(to);
					int selectedIndex = model.getIndexOf(to);
					if (selectedIndex < 0) {
						// if the selected book does not exist before, 
						// add it into this combo box
						model.addElement(to);
					}
    }//GEN-LAST:event_jComboBox2ActionPerformed

    
    private void GdanskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GdanskActionPerformed
      

        
    }//GEN-LAST:event_GdanskActionPerformed

    private void SzczecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzczecinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SzczecinActionPerformed
    

 
        
     
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.ButtonGroup CitiesGroup;
    private javax.swing.JTextField From;
    private javax.swing.JButton Gdansk;
    private javax.swing.JButton Szczecin;
    private javax.swing.JTextField To;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
